### ISSUE TITLE
Configure local graph-node

### ISSUE THREAD

**Issue by angelorc** [figment-networks/firehose-cosmos#28]
Hello there,
I'm trying to figure out how to connect the firehose-cosmos to a local graph-node instance.

Is there any variable as endpoint to set?

Ty

**Comment by lavabyrd** [comment]
Hey @angelorc , 

I believe we discussed this over discord so I'll close this for now! Thanks!

**Comment by angelorc** [comment]
Alright, however it will be better to improve the docs. I will try to do my support
